enum DIRECTION {
  UP,
  DOWN,
  LEFT,
  RIGHT,
}

export type Monster = {
  name: string
  /** Animations to be generated by this monster */
  animations: {
    directions: {
      [key: number]: {
        start: number
        end: number
      }
    }
    /** Idle frame */
    idle: number
  }
  /** Sprite sheet key for the monster to use animations, etc. */
  spriteKey: string
}

const Goblin: Monster = {
  name: "Goblin",
  animations: {
    idle: 79,
    directions: {
      [DIRECTION?.UP]: {
        start: 85,
        end: 87,
      },
      [DIRECTION?.DOWN]: {
        start: 79,
        end: 81,
      },
      [DIRECTION?.LEFT]: {
        start: 88,
        end: 90,
      },
      [DIRECTION?.RIGHT]: {
        start: 82,
        end: 84,
      },
    },
  },
  spriteKey: "creatures_01",
}
export default Goblin
